### ISSUE TITLE
Question about beta matrix file

### ISSUE THREAD

**Issue by TahirahYasmin** [hamidghaedi/Methylation_Analysis#2]
Hello!
I only have a beta matrix file containing the probe IDs and methylation beta values. I do not have idat files. Can I use your code to directly analyse this data? I am quite new to this field.
Thanks a lot in advance!

**Comment by hamidghaedi** [comment]
Thanks for showing your interest in using the code for your analysis. 
Yes, you can.  Actually, this tutorial starts taking a matrix of values as input.

**Comment by TahirahYasmin** [comment]
Thank you!
